// Original concise reading notes, using the Rider–Waite–Smith card sequence.
// These are interpretive prompts, not quotations or translations of Waite.
const majors = [
  ['愚者','The Fool','新旅程 · 信任 · 好奇','Beginnings · Trust · Curiosity','给未知留一点空间，以小步尝试新的方向。','Leave room for the unknown; try a new direction in small steps.','冲动或迟疑都可能让你忽略现实条件，先检查脚下的路。','Impulsiveness or hesitation may obscure practical limits; check your footing.'],
  ['魔术师','The Magician','意志 · 技能 · 创造','Will · Skill · Creation','把已有的工具、经验与想法组合起来，采取具体行动。','Bring your tools, experience and ideas together in a concrete action.','能力需要聚焦，留意空谈、分散精力或操控的倾向。','Focus your abilities; watch for empty promises, distraction or manipulation.'],
  ['女祭司','The High Priestess','直觉 · 静观 · 隐秘','Intuition · Stillness · Mystery','暂缓定论，倾听直觉，也观察尚未说出口的信息。','Pause before concluding; listen inward and notice what remains unspoken.','直觉可能被噪声遮住，辨别内在感受与未经证实的猜测。','Separate inner knowing from noise and unverified assumptions.'],
  ['皇后','The Empress','滋养 · 丰盛 · 生长','Nurture · Abundance · Growth','照顾身体、关系与创意，让成果在耐心中生长。','Care for your body, relationships and ideas; let growth take its time.','过度付出或依赖可能耗尽自己，恢复照顾自己的节奏。','Overgiving or dependence may drain you; restore self-care.'],
  ['皇帝','The Emperor','结构 · 边界 · 责任','Structure · Boundaries · Responsibility','建立清楚的规则和边界，以稳定的行动承担责任。','Set clear rules and boundaries; take responsibility through steady action.','僵硬控制或缺少秩序都值得调整，为规则保留弹性。','Rebalance rigid control or missing structure; leave room for flexibility.'],
  ['教皇','The Hierophant','传统 · 学习 · 共同价值','Tradition · Learning · Shared values','借助可靠的知识、导师或共同原则，为选择找到依据。','Seek reliable knowledge, mentors or shared principles to ground a choice.','检视习惯是否适合当下，也给独立思考留出位置。','Question whether inherited habits fit the present; think independently.'],
  ['恋人','The Lovers','选择 · 联结 · 一致','Choice · Connection · Alignment','让行动与价值一致，在关系中坦诚表达彼此的选择。','Align action with values and speak honestly about mutual choices.','留意价值冲突、犹豫或失衡，先厘清真正愿意承诺什么。','Clarify conflicting values, hesitation and what you can truly commit to.'],
  ['战车','The Chariot','方向 · 自律 · 推进','Direction · Discipline · Momentum','把不同力量带向同一目标，以自律保持前进。','Direct competing forces toward one goal and move with discipline.','急于推进或方向失散时，重新确认目标与可控的节奏。','If momentum becomes force or confusion, reset your aim and pace.'],
  ['力量','Strength','勇气 · 温柔 · 耐心','Courage · Gentleness · Patience','用耐心与温柔处理强烈情绪，坚定也可以不靠强迫。','Meet strong feelings with patience; firmness need not become force.','照顾疲惫与自我怀疑，避免用压抑代替真正的安定。','Care for exhaustion and doubt; suppression is not inner steadiness.'],
  ['隐者','The Hermit','独处 · 省思 · 指引','Solitude · Reflection · Guidance','给自己安静的时间，辨认什么值得继续投入。','Take quiet time to discern what deserves your continued attention.','独处若变成封闭，适时向值得信任的人寻求连接。','If solitude becomes isolation, reach toward trustworthy connection.'],
  ['命运之轮','Wheel of Fortune','周期 · 转机 · 变化','Cycles · Turning points · Change','承认环境在变化，观察时机并调整可以改变的部分。','Notice changing circumstances and respond where you have influence.','反复受阻可能提示旧模式，放下对所有结果的控制。','Repeated setbacks may reveal a pattern; release total control.'],
  ['正义','Justice','公平 · 因果 · 判断','Fairness · Consequences · Judgment','据事实作判断，考虑选择的后果并承担自己的部分。','Judge by evidence, consider consequences and own your part.','重新检查偏见、遗漏或回避的责任，补足信息再决定。','Revisit bias, missing facts or avoided responsibility before deciding.'],
  ['倒吊人','The Hanged Man','暂停 · 换位 · 放下','Pause · Perspective · Release','暂时放慢，换一个角度看问题，放下无效的用力。','Slow down and change perspective; release effort that no longer helps.','分辨有意义的等待与拖延，明确暂停的边界。','Distinguish useful waiting from avoidance; give the pause a boundary.'],
  ['死神','Death','结束 · 转化 · 更新','Endings · Transformation · Renewal','为已经完成的阶段收尾，让新的生活方式获得空间。','Close a completed chapter and make room for a new way of living.','抗拒结束可能让过渡更困难，循序放下不再适合的模式。','Resistance can prolong a transition; release outdated patterns gradually.'],
  ['节制','Temperance','调和 · 节奏 · 整合','Balance · Pace · Integration','尝试兼容不同需求，以适度和持续的节奏做调整。','Blend different needs through moderation and sustainable adjustments.','留意失衡、过度或急躁，找回能够长期维持的尺度。','Notice excess or impatience and recover a sustainable measure.'],
  ['恶魔','The Devil','束缚 · 欲望 · 觉察','Attachment · Desire · Awareness','看见习惯、依赖或诱惑如何限制选择，辨认可松开的束缚。','Notice how habits and attachments narrow choice; identify a loosenable bond.','你可能开始看见旧束缚，以支持与具体行动恢复自主。','Awareness of an old attachment can support practical steps toward freedom.'],
  ['高塔','The Tower','动摇 · 揭露 · 重建','Disruption · Revelation · Rebuilding','当旧结构被挑战，先稳住基本需要，再据事实重建。','When an old structure is challenged, secure essentials and rebuild from facts.','回避必要改变可能积累压力，小范围修正比持续掩盖更有帮助。','Avoiding necessary change may build pressure; begin manageable repairs.'],
  ['星星','The Star','希望 · 恢复 · 灵感','Hope · Renewal · Inspiration','以温和的小行动恢复信心，让希望有现实的落脚点。','Restore confidence through gentle actions that give hope a practical home.','失望不必成为最终结论，重新寻找支持与可达的小目标。','Disappointment need not be final; find support and a reachable next step.'],
  ['月亮','The Moon','不确定 · 潜意识 · 想象','Uncertainty · Subconscious · Imagination','在信息不清楚时保留判断，辨别情绪、想象与事实。','Hold judgment amid uncertainty; distinguish feeling, imagination and fact.','迷雾可能正在散开，也可能是压下了疑虑，逐一核实。','Uncertainty may be clearing, or concerns suppressed; verify one at a time.'],
  ['太阳','The Sun','清晰 · 活力 · 喜悦','Clarity · Vitality · Joy','珍惜清楚的理解与合作，让真诚和活力带动行动。','Use clarity, sincerity and shared energy to support action.','短暂低落或过高期待可能遮住已有成果，重拾简单的快乐。','Low spirits or inflated expectations may hide progress; return to simple joy.'],
  ['审判','Judgement','回顾 · 觉醒 · 回应','Review · Awakening · Response','回看经验，回应真正重要的召唤，做出更有意识的选择。','Review experience and respond consciously to what matters most.','苛责或逃避可能妨碍更新，用诚实与宽容重新评估。','Harsh judgment or avoidance may stall renewal; reassess with compassion.'],
  ['世界','The World','完成 · 整合 · 归属','Completion · Integration · Belonging','承认一个阶段的完成，整合收获并准备下一段旅程。','Recognise completion, integrate what you have learned and prepare to continue.','尚有收尾工作或未被看见的成就，给过程一个完整的结束。','Attend to unfinished details and unrecognised progress; close the loop.'],
];
const suits = [
  { key:'wands', zh:'权杖', en:'Wands', element:{zh:'火 · 行动与创造',en:'Fire · Action & creativity'}, rows:[
    ['新的灵感值得试探，让一个想法获得起点。','A fresh idea deserves a first experiment.','动力暂时不足，先确认你真正想开始什么。','Clarify what you wish to begin before forcing momentum.'],
    ['放眼更大的可能，为下一步拟定计划。','Survey your options and plan a next step.','犹豫或过度规划可能拖慢行动，缩小第一步。','Reduce the first step if hesitation or overplanning stalls action.'],
    ['已有行动开始打开空间，留意合作与长远发展。','Early efforts open possibilities for cooperation and expansion.','等待结果时检查条件，调整不切实际的期待。','Review conditions and expectations while waiting for results.'],
    ['分享阶段性的成果，巩固支持你的人与环境。','Celebrate a milestone and strengthen a supportive base.','归属感或协作需要照顾，先修复基础。','Attend to belonging and cooperation; repair the foundation.'],
    ['竞争与不同意见能够推动学习，保持建设性的讨论。','Let competing views sharpen learning through constructive discussion.','反复争执或回避冲突都可能耗能，找回共同目标。','Move beyond recurring conflict or avoidance toward a shared aim.'],
    ['看见自己的进步，也把认可分享给同行者。','Recognise progress and share credit with those alongside you.','外界认可不足时，回到真正的进步而非表面比较。','Return to meaningful progress rather than comparison or applause.'],
    ['为重要的立场设边界，选择值得坚持的事。','Defend a meaningful position and choose worthwhile boundaries.','持续防备可能让人疲惫，分辨哪些对抗可以放下。','Constant defensiveness drains energy; choose what can be released.'],
    ['事情正在加速，清楚沟通并及时安排优先次序。','As events accelerate, communicate clearly and prioritise.','节奏混乱或消息延迟时，避免仓促下判断。','Avoid rushed conclusions amid delay or scattered momentum.'],
    ['已有经验帮助你坚持，也要给自己休息的余地。','Experience supports persistence; protect space for recovery too.','警惕与疲惫需要照顾，寻求支持而非独自硬撑。','Care for fatigue and vigilance; seek support instead of enduring alone.'],
    ['责任可能过重，整理负担并学习分担。','Review heavy responsibilities and share the load.','可以放下不属于自己的负担，也检查是否逃避必要责任。','Release needless burdens while checking essential responsibilities.'],
    ['以好奇探索新的方向，用小尝试累积经验。','Explore with curiosity and learn through small trials.','灵感需要落实，避免因一时热情频繁换方向。','Ground inspiration instead of changing direction on every impulse.'],
    ['带着热情推进，但为速度配上清楚的目标。','Move with enthusiasm and a clear destination.','急躁或反复可能妨碍兑现承诺，放慢再行动。','Slow impulsiveness and inconsistency to honour commitments.'],
    ['自信表达你的创意，也为他人的成长留出空间。','Express creativity confidently and support others in growing.','自我怀疑或攀比会消耗热情，恢复自己的节奏。','Recover your own rhythm from self-doubt or comparison.'],
    ['用远见带领行动，把愿景转化为持续的投入。','Lead with vision and translate it into sustained action.','留意强势、急切或不切实际的要求，调整领导方式。','Rebalance demanding or impatient leadership with realistic expectations.'],
  ]},
  { key:'cups', zh:'圣杯', en:'Cups', element:{zh:'水 · 情感与关系',en:'Water · Feeling & connection'}, rows:[
    ['接纳新的感受或关系，让情绪有被表达的空间。','Welcome new feelings and give them room for expression.','先照顾情绪的容量，避免压抑或过度投入。','Care for emotional capacity before suppressing or overinvesting.'],
    ['建立互相尊重的联结，坦诚交流需要与边界。','Build reciprocal connection through honest needs and boundaries.','关系中的失衡需要对话，确认双方真实的意愿。','Address imbalance and clarify mutual willingness.'],
    ['在友谊与共同庆祝中获得支持，珍惜协作。','Find support in friendship, celebration and collaboration.','群体关系或社交过量需要调整，辨别真正的支持。','Review group dynamics and excessive social demands.'],
    ['给不满足一点观察时间，也留意身边可用的机会。','Observe dissatisfaction while noticing opportunities nearby.','新的兴趣可能出现，别急着否定或勉强自己。','Make room for renewed interest without forcing yourself.'],
    ['承认失落，同时看见仍然存在的资源与关系。','Acknowledge loss and notice what remains available.','逐渐松开遗憾，允许支持帮助你重新出发。','Let support help you loosen regret and begin again.'],
    ['从回忆、善意与熟悉的关系中取回温柔。','Draw gentleness from memory, kindness and familiar connection.','怀旧若遮住现在，更新你对旧关系的理解。','Update old attachments when nostalgia obscures the present.'],
    ['多种可能需要分辨，把想象转成可核实的选择。','Discern among possibilities and turn imagination into testable choices.','选项渐清或逃避选择，都是重新聚焦的提示。','Clarify narrowing options or avoidance and refocus.'],
    ['当旧投入不再滋养你，诚实评估是否需要离开。','Assess whether a once-meaningful commitment still nourishes you.','犹豫离开时厘清原因，避免只为逃避而转身。','Clarify hesitation and avoid leaving solely to escape discomfort.'],
    ['珍惜当前的满足，同时留意愿望背后的真实需要。','Appreciate contentment and understand the need behind a wish.','外在拥有未必带来满足，重看你真正重视的事。','Revisit what matters when outward plenty feels unsatisfying.'],
    ['共同的价值与情感支持值得经营，幸福也需要实践。','Cultivate shared values and emotional support through everyday care.','理想画面与实际关系可能有差距，诚实交流。','Speak honestly about gaps between an ideal picture and real connection.'],
    ['以温柔和好奇接近感受，让创意或善意被表达。','Meet feelings with curiosity and express imagination or kindness.','留意情绪反复或不切实际的想象，学习更直接地表达。','Ground shifting feelings and communicate more directly.'],
    ['让理想与感受带动行动，也保持真诚与现实感。','Let ideals inspire sincere and grounded action.','辨别真诚承诺与一时浪漫，不以想象替代了解。','Distinguish sincere commitment from romantic projection.'],
    ['倾听细微的情绪，带着同理心照顾自己与他人。','Listen closely and care with empathy for yourself and others.','情绪边界值得维护，避免把所有人的需要都承担下来。','Maintain emotional boundaries instead of carrying every need.'],
    ['在感受与判断间保持平衡，以成熟的方式沟通。','Balance feeling and judgment through mature communication.','情绪失控或被压住时，先安定自己再处理关系。','Regain steadiness before responding to emotional turbulence.'],
  ]},
  { key:'swords', zh:'宝剑', en:'Swords', element:{zh:'风 · 思考与沟通',en:'Air · Thought & communication'}, rows:[
    ['以清楚的问题和事实切入，形成新的理解。','Begin with a precise question and evidence for a new understanding.','信息混乱时重新核实，避免用强硬代替清晰。','Verify confusion rather than replacing clarity with force.'],
    ['僵持的选择需要更多信息，也需要面对自己的顾虑。','A stalled choice needs information and honest concerns.','回避可能暂时结束，逐步拆解过载的信息。','Break down overload as avoidance becomes harder to sustain.'],
    ['承认伤心或失望，给真实的感受与对话留空间。','Acknowledge hurt and allow honest feeling and conversation.','修复可以缓慢进行，留意尚未被处理的痛苦。','Allow gradual repair and attend to unresolved pain.'],
    ['暂停争论或忙碌，休息有助于恢复判断。','Rest from conflict or busyness to restore judgment.','休息不足或停滞过久时，重新安排恢复与行动。','Rebalance recovery and action after exhaustion or prolonged inactivity.'],
    ['考虑争胜的代价，选择更值得维护的关系与原则。','Consider the cost of winning and protect meaningful values.','修复争执时坦诚面对损伤，避免把问题继续埋下。','Address damage honestly when attempting reconciliation.'],
    ['带着经验离开混乱，允许过渡逐步展开。','Carry lessons toward calmer conditions and allow transition.','旧问题仍可能随行，明确需要面对而非带走的部分。','Identify unresolved issues rather than carrying them unchanged.'],
    ['策略与独立判断很重要，也检查行动是否诚实。','Use strategy and independent thought while checking integrity.','隐瞒或回避可能难以继续，以坦诚修正路线。','Correct a path through honesty when avoidance no longer works.'],
    ['检视限制中哪些来自事实，哪些来自固有的看法。','Distinguish practical constraints from inherited assumptions.','你可能看见新的余地，以小行动恢复选择感。','Recover agency through small actions as possibilities become visible.'],
    ['焦虑需要被倾听，把担忧拆解成可以处理的部分。','Listen to worry and break it into manageable concerns.','寻求支持有助于恢复，留意是否只是把忧虑压下。','Seek support and distinguish recovery from suppressed anxiety.'],
    ['承认一个困难阶段的结束，先照顾恢复与收尾。','Recognise a difficult ending and attend to recovery.','恢复需要耐心，也检查是否仍抓着已结束的模式。','Give recovery time and release patterns that have run their course.'],
    ['保持求知与观察，先提问再作结论。','Stay curious and observe before drawing conclusions.','留意流言、仓促判断或过度警惕，核实来源。','Verify sources instead of feeding gossip or hasty judgments.'],
    ['果断表达目标，同时为速度配上倾听和核实。','Express a goal decisively, with listening and verification.','争辩或鲁莽会偏离目标，放慢并补足信息。','Slow argument or rash action and fill information gaps.'],
    ['以清楚的边界与诚实的沟通处理复杂问题。','Handle complexity with clear boundaries and honest communication.','过度尖锐或封闭可能阻碍理解，为判断保留同理心。','Temper sharpness or detachment with empathy.'],
    ['以逻辑、原则与专业知识作出有依据的决定。','Use logic, principles and expertise for a grounded decision.','警惕武断或滥用话语权，允许事实修正观点。','Allow evidence to correct dogmatism or misuse of authority.'],
  ]},
  { key:'pentacles', zh:'星币', en:'Pentacles', element:{zh:'土 · 生活与资源',en:'Earth · Life & resources'}, rows:[
    ['现实中的新机会值得评估，以务实的第一步培育它。','Evaluate a tangible opportunity and nurture it with a practical step.','先核对资源与条件，避免仓促承诺或错过准备。','Check resources and readiness before committing.'],
    ['在多个任务间灵活安排，也给节奏留出缓冲。','Balance competing tasks with flexibility and a margin.','失衡可能说明承担过多，重新排序并减少负担。','Reduce overload and reprioritise when balance slips.'],
    ['让各自的技能在协作中发挥，重视学习与反馈。','Combine complementary skills and value learning and feedback.','沟通或分工需要改善，重新确认共同的标准。','Clarify roles, communication and shared standards.'],
    ['稳固资源与边界，同时观察是否握得过紧。','Secure resources while noticing an overly tight grip.','整理对安全感的执着，在分享与保护间找尺度。','Rebalance security, protection and sharing.'],
    ['困难值得承认，也留意可以求助的资源与支持。','Acknowledge hardship and notice available support.','支持可能开始出现，允许自己寻求与接受帮助。','Recognise emerging support and allow yourself to receive it.'],
    ['在给予与接受间保持尊重、公平和清楚的边界。','Give and receive with respect, fairness and boundaries.','检视交换中的权力与条件，避免不对等的依赖。','Review power and conditions in unequal exchanges.'],
    ['停下来评估投入与成果，让长期目标指导调整。','Review effort and results before refining a long-term plan.','耐心不足或投入失当时，重算成本与实际进度。','Reassess effort and progress when impatience or poor fit grows.'],
    ['通过练习和专注打磨技能，重视持续的小改进。','Develop skill through focused practice and small improvements.','机械重复或完美主义可能耗能，找回学习目的。','Recover purpose from mechanical work or perfectionism.'],
    ['珍惜努力带来的独立与安定，也照顾生活的质量。','Appreciate earned independence and attend to quality of life.','比较或过度依赖可能削弱满足，厘清自己的需要。','Clarify personal needs beyond comparison or dependence.'],
    ['关注长远稳定、共同资源与代际的支持关系。','Consider lasting stability, shared resources and interdependence.','既定结构或资源分配需要调整，沟通共同的期待。','Review established arrangements and communicate shared expectations.'],
    ['带着认真与好奇学习，把目标化为具体的练习。','Learn with curiosity and turn a goal into concrete practice.','拖延或只停留在计划时，找一个可完成的小任务。','Move beyond plans or procrastination through one doable task.'],
    ['用稳定的节奏履行承诺，细节会积累成成果。','Keep commitments steadily; details build progress.','例行事务可能变得僵化，调整方法而非失去耐心。','Adapt rigid routines without abandoning steadiness.'],
    ['以务实的照顾经营生活，让资源支持人的需要。','Care practically so resources serve human needs.','过度操心或忽略自身时，重建照顾与工作的边界。','Restore boundaries when worry or caretaking eclipses your needs.'],
    ['稳健运用经验与资源，为长期发展建立基础。','Use experience and resources responsibly for lasting foundations.','检视物质执着、控制或失衡，回到资源的真实用途。','Revisit attachment or control and the true purpose of resources.'],
  ]},
];
const ranksZH=['王牌','二','三','四','五','六','七','八','九','十','侍从','骑士','王后','国王'];
const ranksEN=['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Page','Knight','Queen','King'];
export const SUITS = Object.freeze(suits.map(({rows,...suit})=>Object.freeze(suit)));
export const CARDS = Object.freeze([
  ...majors.map(([zh,en,kzh,ken,uzh,uen,rzh,ren],id)=>({id,suit:'major',rank:id,
    name:{zh,en},keywords:{zh:kzh,en:ken},upright:{zh:uzh,en:uen},reversed:{zh:rzh,en:ren}})),
  ...suits.flatMap((suit,s)=>suit.rows.map(([uzh,uen,rzh,ren],r)=>({id:22+s*14+r,suit:suit.key,rank:r+1,
    name:{zh:`${suit.zh}${ranksZH[r]}`,en:`${ranksEN[r]} of ${suit.en}`},keywords:suit.element,
    upright:{zh:uzh,en:uen},reversed:{zh:rzh,en:ren}}))),
].map(card=>Object.freeze({...card,...Object.fromEntries(['name','keywords','upright','reversed'].map(key=>[key,Object.freeze(card[key])]))})));
export const SPREADS = Object.freeze({
  single:{count:1,name:{zh:'一张牌 · 此刻',en:'One card · The present'},hint:{zh:'给眼前的问题一个清楚的切入点。',en:'A clear starting point for what is on your mind.'},positions:{zh:['此刻的提示'],en:['A message for now']}},
  three:{count:3,name:{zh:'三张牌 · 流动',en:'Three cards · The unfolding'},hint:{zh:'看见来处、当下与可能的方向。',en:'Explore what led here, what is present and what may unfold.'},positions:{zh:['来处与背景','当下的状态','可能的方向'],en:['Background','The present','Possible direction']}},
  cross:{count:5,name:{zh:'五张牌 · 探索',en:'Five cards · An exploration'},hint:{zh:'把处境、阻力与可用的支持放在一起看。',en:'Consider the situation, friction and resources together.'},positions:{zh:['核心处境','需要面对的阻力','可用的支持','可以尝试的行动','可能的发展'],en:['The situation','The challenge','Your support','An action to try','Possible development']}},
});
