export const TEXT = {
  en: {
    title:'Arcana · A moment of reflection', description:'A quiet space for tarot. Explore 78 cards, draw a spread and reflect with Gemini in English or Chinese.',
    skip:'Skip to the reading', brand:'Arcana', brandSub:'A TAROT JOURNAL', nav:'Main navigation', language:'Language', navReading:'Reading', navCards:'The cards', navGuide:'A little guidance', journal:'My journal',
    heroEyebrow:'A MOMENT OF REFLECTION', heroFirst:'Let the cards', heroSecond:'meet you here.', heroDescription:'A question. A pause. A different perspective.\nFind a quiet moment with the language of symbols.', heroLink:'Begin a reading', artCaption:'The answer begins with a question.', footDeck:'78 cards · An original symbolic deck', footPause:'Draw slowly. Read thoughtfully.',
    readingTitle:'Make room for a question', readingSubtitle:'One moment, one intention.', questionLabel:'WHAT IS ON YOUR MIND?', optional:'Optional', questionPlaceholder:'What would you like to understand more clearly?', questionPrivacy:'Your question stays here until you ask AI.', spreadLabel:'Choose your spread', useReversals:'Include reversed cards', shuffle:'Shuffle & begin', randomNote:'Shuffled with your browser’s secure random source.', tableLabel:'THE CARDS · YOUR MOMENT', tableEmpty:'A little stillness before the first card.', pickHint:'Choose a card that catches your attention.', autoDraw:'Draw the remaining cards →',
    aiButton:'Read with AI ✧', save:'Save to journal', reset:'Start again', aiPrivacy:'Only when you ask: your question and drawn cards go through Appwrite or Cloudflare to Google Gemini.', resultEyebrow:'YOUR SPREAD /', resultTitle:'Look a little closer', export:'Export this reading ↓', aiEyebrow:'A SECOND PERSPECTIVE · GEMINI', aiTitle:'A reading to reflect on', partial:'The answer reached its length limit; it may be incomplete.', aiNote:'A symbolic reflection, with room for your own judgment.', cancel:'Stop waiting', retry:'Read again ↻',
    guideTitle:'An invitation, not a verdict', guideOne:'Ask an open question', guideOneText:'“What could I understand?” leaves more space than asking for a fixed yes or no.', guideTwo:'Read the whole picture', guideTwoText:'Notice the position, orientation and relationships between cards. A reversed card is not automatically bad.', guideThree:'Bring it back to life', guideThreeText:'Keep what helps you reflect, then choose one practical action. The cards do not make the choice for you.',
    methodTitle:'About this deck, randomness & privacy', methodText:'All 78 cards follow the Rider–Waite–Smith sequence. The vector illustrations and brief notes are original interpretations. Shuffling uses Web Crypto and unbiased sampling, without replacement. Reversals have equal probability when enabled. This is a reflective experience, not a prediction of definite events.', languagePrivacy:'To choose a default language, the page may query Country.is for your network’s country. That service receives your IP, never your question or cards. Only the country code is used; your IP is not stored. Manual language choice takes priority. If lookup fails, browser language is used.', storageNote:'Only readings you explicitly save enter this browser’s local journal. AI answers are not saved or exported. Clearing browser storage removes the journal.', countrySource:'About Country.is ↗',
    libraryTitle:'The language of 78 cards', search:'Search a card', noCards:'No cards found. Try another name.', footer:'A quiet moment. A wider perspective.', ichingLink:'Visit I Ching ↗', close:'Close', journalNote:'Saved in this browser only.', noJS:'JavaScript is required to shuffle and read the cards.',
    all:'All cards', major:'Major Arcana', wands:'Wands', cups:'Cups', swords:'Swords', pentacles:'Pentacles', upright:'Upright', reversed:'Reversed', bothMeanings:'Explore both orientations', cardNumber:'Card', noQuestion:'An open reading · No question entered', drawProgress:'{drawn} / {total} cards', chooseNext:'Choose card {number} · {position}', drawComplete:'Your spread is ready. Take a moment to notice what stands out.', pickCard:'Choose face-down card {number}', cardsCount:'{count} cards', aiSelecting:'Finding an available AI connection…', aiGenerating:'Reflecting on your question and cards…', aiComplete:'Reading complete', aiCancelled:'Waiting stopped. You can request a reading again.', cloudflare:'Cloudflare', appwrite:'Singapore', saved:'Saved to your journal', alreadySaved:'This reading is already in your journal.', saveFailed:'Browser storage is unavailable. You can export this reading instead.', exported:'Reading exported', historyEmpty:'Your journal is waiting for its first reading.', openReading:'Open reading', deleteReading:'Delete', deleted:'Reading removed', randomError:'Secure randomness is unavailable. Use a modern browser over HTTPS or localhost.', sourceIP:'Default language: IP region ({country})', sourceBrowser:'Default language: browser preference', sourceManual:'Language: your choice', returnToReading:'Reading opened',
    error400:'This reading is incomplete. Please draw a new spread.', error403:'This website is not authorised to use the AI service.', error404:'The AI endpoint is unavailable.', error413:'Please shorten your question.', error422:'Gemini could not produce a reading. Try again later or rephrase your question.', error429:'Too many requests or Gemini quota is temporarily unavailable. Please wait before trying again.', error502:'Gemini could not finish this reading. Please try again later.', error503:'The AI service is not ready. Please try again later.', error504:'The reading timed out. Please try again later.', errorNETWORK:'The AI service could not be reached. Check your connection and try again.', errorROUTE:'No available connection supports tarot yet. Please try again later.', errorRESPONSE:'The AI service returned an unexpected response. Please try again later.', errorCONFIG:'The AI connection is not configured correctly.', errorUNKNOWN:'The reading could not be completed. Please try again later.',
  },
  zh: {
    title:'星镜 · 塔罗占卜', description:'在安静片刻探索 78 张塔罗牌，抽取牌阵，以中文或英文获得 Gemini 解读。',
    skip:'跳到占卜', brand:'星镜', brandSub:'塔罗 · 观照日记', nav:'主导航', language:'页面语言', navReading:'开始占卜', navCards:'认识牌面', navGuide:'阅读指引', journal:'我的日记',
    heroEyebrow:'留一个片刻，听见自己', heroFirst:'让一张牌，', heroSecond:'照见此刻的你。', heroDescription:'一个问题，一次停顿，一种新的视角。\n在象征的语言里，为自己留一刻安静。', heroLink:'开始一次占卜', artCaption:'解读，从一个问题开始。', footDeck:'78 张牌 · 原创象征牌面', footPause:'慢慢抽牌，细细观照。',
    readingTitle:'为心中的问题留一个位置', readingSubtitle:'此刻，一事，一念。', questionLabel:'你想了解什么？', optional:'选填', questionPlaceholder:'此刻的你，希望更清楚地理解什么？', questionPrivacy:'点击 AI 解读前，问题只留在此页面。', spreadLabel:'选择牌阵', useReversals:'包含逆位牌', shuffle:'洗牌，开始占卜', randomNote:'使用浏览器的安全随机源洗牌。', tableLabel:'塔罗成象 · 此刻的你', tableEmpty:'抽出第一张牌之前，先静一静。', pickHint:'从牌背中，选一张吸引你的牌。', autoDraw:'自动抽出剩余的牌 →',
    aiButton:'AI 解读牌阵 ✧', save:'保存到日记', reset:'重新占卜', aiPrivacy:'仅在点击 AI 解读时，问题和抽出的牌会经 Appwrite 或 Cloudflare 发送给 Google Gemini。', resultEyebrow:'你的牌阵 /', resultTitle:'再看深一点', export:'导出本次占卜 ↓', aiEyebrow:'另一种视角 · GEMINI', aiTitle:'一份供你思考的解读', partial:'回答达到长度上限，内容可能不完整。', aiNote:'以象征启发思考，判断仍留给自己。', cancel:'停止等待', retry:'再次解读 ↻',
    guideTitle:'一种邀请，而非定论', guideOne:'问一个开放的问题', guideOneText:'“我可以理解什么？”比一个固定的“是或否”，留下更多思考的空间。', guideTwo:'看见牌阵的整体', guideTwoText:'结合牌位、正逆位，以及牌与牌之间的联系。逆位不自动意味着坏事。', guideThree:'把解读带回生活', guideThreeText:'留下对你有帮助的启发，再选择一个实际行动。牌不会替你作决定。',
    methodTitle:'关于牌面、随机性与隐私', methodText:'完整 78 张牌采用韦特—史密斯体系的顺序。矢量牌面和简要牌意均为原创表达。洗牌使用 Web Crypto 安全随机数与无偏采样，不重复抽取；启用逆位时，正逆位概率各为一半。占卜用于自我观照，不预测必然发生的事件。', languagePrivacy:'页面可能向 Country.is 查询网络出口所在国家或地区，以选择默认语言。该服务能看到你的 IP，但不会收到问题或牌阵。页面仅使用国家代码，不保存 IP。手动选择的语言优先；查询失败时采用浏览器语言。', storageNote:'只有你主动保存的占卜才进入当前浏览器的本地日记。AI 回答不保存、不导出。清除浏览器存储会移除日记。', countrySource:'了解 Country.is ↗',
    libraryTitle:'认识 78 张牌的语言', search:'搜索牌名', noCards:'未找到牌面，请试试其他名字。', footer:'片刻的安静，更宽的视角。', ichingLink:'前往周易占筮 ↗', close:'关闭', journalNote:'仅保存在当前浏览器。', noJS:'洗牌与占卜需要启用 JavaScript。',
    all:'全部牌', major:'大阿尔卡那', wands:'权杖', cups:'圣杯', swords:'宝剑', pentacles:'星币', upright:'正位', reversed:'逆位', bothMeanings:'展开正逆位牌意', cardNumber:'牌', noQuestion:'自由占卜 · 未填写问题', drawProgress:'已抽 {drawn} / {total} 张', chooseNext:'请选择第 {number} 张 · {position}', drawComplete:'牌阵已成。先留意，哪一张牌触动了你？', pickCard:'选择第 {number} 张背面牌', cardsCount:'{count} 张牌', aiSelecting:'正在寻找可用的 AI 线路…', aiGenerating:'正在结合所问之事与牌阵解读…', aiComplete:'解读已完成', aiCancelled:'已停止等待，可再次请求解读。', cloudflare:'Cloudflare 线路', appwrite:'新加坡线路', saved:'已保存到日记', alreadySaved:'本次占卜已在日记中。', saveFailed:'浏览器存储不可用，可以导出本次占卜。', exported:'已导出本次占卜', historyEmpty:'日记正等待你的第一次记录。', openReading:'查看占卜', deleteReading:'删除', deleted:'记录已删除', randomError:'安全随机源不可用，请在现代浏览器中通过 HTTPS 或本机预览访问。', sourceIP:'默认语言：IP 所在地区（{country}）', sourceBrowser:'默认语言：浏览器偏好', sourceManual:'页面语言：你的选择', returnToReading:'已打开这次占卜',
    error400:'本次牌阵资料不完整，请重新抽牌。', error403:'当前网站尚未获准使用 AI 服务。', error404:'AI 接口暂不可用。', error413:'请缩短你的问题。', error422:'Gemini 未能生成解读，请稍后再试或调整问题。', error429:'请求较多或 Gemini 额度暂时不足，请稍后再试。', error502:'Gemini 暂时无法完成解读，请稍后再试。', error503:'AI 服务尚未就绪，请稍后再试。', error504:'本次解读等待超时，请稍后重试。', errorNETWORK:'无法连接 AI 服务，请检查网络后重试。', errorROUTE:'暂时没有可用的塔罗解读线路，请稍后再试。', errorRESPONSE:'AI 服务返回内容异常，请稍后再试。', errorCONFIG:'AI 线路配置有误。', errorUNKNOWN:'本次解读未能完成，请稍后再试。',
  },
};
export function translate(lang, key, values={}) {
  const template=TEXT[lang]?.[key] ?? TEXT.en[key];
  if(typeof template!=='string') throw new Error(`Missing translation: ${key}`);
  return template.replace(/\{(\w+)\}/g,(_,name)=>String(values[name]??''));
}
